techno/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webapp/', include('webapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/urls.py
from django.urls import path

from .views import EmployeeList, EmployeeCreateView, update_employee, JobsList, ToolList, ToolCreateView, JobCreateView, \
        BreakdownList, BreakdownCreateView, MachineList, PerformsCreateView, get_shift_efficiency, \
        get_total_avg_efficiency, delete_employee_by_ssn, get_number_of_jobs, get_number_of_machines, \
        get_number_of_employees, get_number_of_tools, shift_eff, shift_performance_by_date, efficiency_by_employee, \
        delete_breakdown_by_tool_code, NMachineList, get_tool_codes, CreateMachineList, \
        calculate_avg_shift_efficiency, LReviving1,NMachineView
from .views import update_tool_view, top_employees, top_least_employees, get_tool_data, tool_chart_details, cacl_avgs, add_to_reviving,shift_counts,tool_codes_view,unique_part_numbers_view,target_by_machine_name,PerformsList
from .views import get_machine_data,delete_machines,delete_tools_by_name,delete_job_by_part_no,display_tool_codes
from .views import get_tool_codess,delete_performs_entry,update_machine
from . import views
# from .views import update_incentives,get_incentives
from .views import check_credentials
from .views import generate_report,calculate_incentive
from .views import update_externals,externals_data,get_tool_codes1,create_external
from .views import breakdown_tool_codes,get_machine_jobs,update_tool,delete_external
from .views import update_incentive




urlpatterns = [
        path('api/employees/', EmployeeList.as_view(), name='employee-list'),
        path('api/employees/create/',EmployeeCreateView.as_view(), name='employee-list-create'),
        path('api/employees/update/<str:pk>/', update_employee),
        path('api/top_employees', top_employees),
        path('api/least_employee', top_least_employees),
        path('api/employees/<str:emp_ssn>/', delete_employee_by_ssn, name='delete_employee_by_ssn'),
        # path('api/breakdown/<path:tool_code>/',add_to_reviving,name="add_to_reviving"),
        path('api/break/<path:tool_code>/<str:date>',add_to_reviving,name="add_to_reviving"),
        path('api/per/', PerformsList.as_view(), name='performs-list'),

        path('performs/<str:date>/<str:emp_ssn>/<int:shift_number>/delete/', delete_performs_entry, name='delete_performs_entry'),

        path('update-machine/<path:machine_id>/', update_machine, name='update_machine'),


        # path('job/', JobList.as_view(), name='job-list'),
        path('tool-codes/<str:part_number>/', get_tool_codess, name='get_tool_codes'),
        path('display-tool-codes/<path:machine_id>/', display_tool_codes, name='display_tool_codes'),

        path('target/<path:machine_name>/', target_by_machine_name, name='target_by_machine_name'),
        path('machinesss/<path:machine_id>/', delete_machines, name='delete_machine'),
        path('delete-tools/<path:tool_name>/<path:tool_code>', delete_tools_by_name, name='delete_tools_by_name'),
        path('delete-job/<path:part_no>/', delete_job_by_part_no, name='delete_job_by_part_no'),

        path('machines/<path:machine_id>/', get_machine_data, name='get_machine_data'),

        path('api/shift_counts/',shift_counts,name='shift_counts'),
        path('api/rev',LReviving1.as_view()),
        path('calculate-shift-efficiency/<path:date_a>/<path:date_b>/<int:shift_number>/', calculate_avg_shift_efficiency, name='calculate_avg_shift_efficiency'),

        path('api/tool_reply/',tool_codes_view,name="toolcodesView"),
        path('api/nmview/',NMachineView.as_view()),
        #counting
         path('num_jobs/',get_number_of_jobs, name='num_jobs'),
         path('num_machines/',get_number_of_machines, name='num_machines'),
         path('num_tools/',get_number_of_tools, name='num_tools'),
         path('num_employees/',get_number_of_employees, name='num_employees'),


        path('api/tools/', ToolList.as_view(), name='tool-list'),

        path('api/tools/create', ToolCreateView.as_view(), name='tool-list-create'),

        path('api/update_tool', update_tool_view),
        path('api/tool_data', get_tool_data),
        path('api/tool_chart/<path:tool_code>', tool_chart_details),

        path('api/performs', PerformsCreateView.as_view()),
        path('api/submit-performance', PerformsCreateView.as_view(), name='performs-create'),


        path('api/jobs/', JobsList.as_view(), name='jobs-list'),
        path('api/jobs/create', JobCreateView.as_view(), name='jobs-list-create'),


        path('api/machines', MachineList.as_view()),
        path('api/nmachines', NMachineList.as_view()),
        path('api/machines/create', CreateMachineList.as_view()),

        path('api/breakdown', BreakdownList.as_view(), name='Break-down-list' ),
        path('api/breakdown/create', BreakdownCreateView.as_view(), name='Break-down-view'),
        path('api/breakdown/<path:tool_code>',delete_breakdown_by_tool_code),
        path('get-tool-codes/<path:part_no>/', get_tool_codes, name='get_tool_codes'),
        path('get-tool-codes1/<path:part_no>/<path:operation_no>/', get_tool_codes1, name='get_tool_codes'),

        path('api/avg/<str:date_a>/<str:date_b>', cacl_avgs),
        path('api/jobss/', unique_part_numbers_view, name='unique_part_numbers'),


        path('shift/<int:shift_number>/', get_shift_efficiency, name='get_shift_efficiency'),
        path('total_avg_efficiency/', get_total_avg_efficiency, name='get_total_avg_efficiency'),
        path('shift_eff/<int:shift_number>',shift_eff),
        path('shift/date', shift_performance_by_date),
        path('emp/efficiency', efficiency_by_employee),


        path('sign-up/', views.sign_up, name='sign_up'),
        path('login/', views.login, name='login'),

        # path('update/<str:category>/<int:incentive>/', update_incentives, name='update_incentives'),
        # path('get_incentives/', get_incentives, name='get_incentives'),

        path('api/check-credentials/', check_credentials, name='check_credentials'),
        path('externals_data/',externals_data),
        path('update_externals/', update_externals, name='update_externals'),

        path('calculate-incentive/<str:emp_ssn>/<str:start_date>/<str:end_date>/', calculate_incentive, name='calculate_incentive'),
        path('generate-report/<str:date>/', generate_report, name='generate_report'),
        path('create_external/',create_external,name='create_external'),
        path('breakdown/<path:tool_code>/tool-codes/', breakdown_tool_codes, name='breakdown_tool_codes'),
        path('api/machine_jobs/<path:machine_id>/', get_machine_jobs, name='get-machine-jobs'),
        path('update_tool/<path:tool_code>/', update_tool, name='update_tool'),

        path('externals/<str:parameter>/delete/', delete_external, name='delete-external'),





        path('check-user/', views.check_user, name='check_user'),
        path('performs/update-incentive/', update_incentive, name='update-incentive'),

]

webapp/models.py
from django.db import models
from django.apps import AppConfig
from datetime import date
from django.db.models.signals import post_save, pre_delete,pre_save,post_delete
from django.shortcuts import get_object_or_404
from django.db.models import F, Sum, Avg
import logging

logger = logging.getLogger(__name__)


# class Incentives(models.Model):
#     category = models.CharField(primary_key=True,max_length=100)
#     incentive = models.IntegerField()

#     def __str__(self):
#         return self.category

class Externals(models.Model):
    parameter = models.CharField(primary_key=True,max_length=100)
    value = models.FloatField()

    def __str__(self):
        return self.parameter



class Employee2(models.Model):
    emp_ssn = models.CharField(primary_key=True, max_length=100)
    emp_name = models.CharField(max_length=100)
    emp_designation = models.CharField(max_length=10)
    emp_shed = models.CharField(max_length=100)
    emp_dept = models.CharField(max_length=100)
    emp_efficiency = models.FloatField(default=0.0)
    emp_category = models.IntegerField()

    def __str__(self):
        return f"{self.emp_ssn}"


class Tool(models.Model):
    tool_code = models.CharField(primary_key=True, max_length=100)
    tool_name = models.CharField(max_length=100)
    max_life_expectancy_in_mm = models.FloatField()
    cost = models.FloatField()
    length_cut_so_far = models.FloatField()
    no_of_brk_points = models.IntegerField(default=None, null=True)
    tool_efficiency = models.FloatField(default=None, null=True)

    def __str__(self):
        return f"{self.tool_code}"


class NewJob(models.Model):
    part_no=models.CharField(primary_key=True,max_length=100)
    def __str__(self):
        return f"{self.part_no}"


class Job(models.Model):
    part_no = models.ForeignKey(NewJob,on_delete=models.CASCADE,db_column='part_no',to_field='part_no')
    component_name = models.CharField(max_length=100)
    depth_of_cut = models.FloatField()
    no_of_holes = models.IntegerField()
    operation_no = models.IntegerField()
    # tool_code = models.ForeignKey(Tool, on_delete=models.CASCADE, db_column='tool_code', to_field='tool_code')
    tool_code = models.ForeignKey(Tool, on_delete=models.SET_NULL, db_column='tool_code', to_field='tool_code', null=True, blank=True)

    class Meta:
        unique_together = ('part_no','component_name','operation_no','tool_code')
    def __str__(self):
        return (f"Part No: {self.part_no}, "
                f"Component Name: {self.component_name}, "
                f"Depth of Cut: {self.depth_of_cut}, "
                f"No of Holes: {self.no_of_holes}, "
                f"Operation No: {self.operation_no}, "
                f"Tool Code: {self.tool_code}")


class NewMachine(models.Model):
    machine_id=models.CharField(primary_key=True,max_length=100)
    def __str__(self):
        return f"{self.machine_id}"


class Machine(models.Model):
    machine_id = models.ForeignKey(NewMachine,on_delete=models.CASCADE,db_column='machine_id')
    machine_name = models.CharField(max_length=100)
    part_no = models.ForeignKey(NewJob, on_delete=models.CASCADE, db_column='part_no')
    tool_code = models.ForeignKey(Tool, on_delete=models.CASCADE, db_column='tool_code')
    target=models.IntegerField()

    class Meta:
        unique_together = ('machine_id', 'tool_code')

    def __str__(self):
        return f"{self.machine_id}"


class Shift(models.Model):
    id = models.BigAutoField(primary_key=True, auto_created=True)
    date = models.DateField()
    shift_number = models.IntegerField()
    shift_efficiency = models.FloatField()

    def __str__(self):
        return f"{self.shift_number}"

class ShiftEfficiency(models.Model):
    shift_number=models.IntegerField(primary_key=True)
    shift_efficiency=models.FloatField()

    def __str__(self):
        return f"{self.shift_number}"

class Performs(models.Model):
    date = models.DateField()
    emp_ssn = models.ForeignKey(Employee2, on_delete=models.CASCADE, db_column='emp_ssn', to_field='emp_ssn')
    machine_id = models.CharField(max_length = 255)
    shift_number = models.IntegerField()
    shift_duration = models.FloatField()
    partial_shift = models.FloatField()
    target = models.IntegerField()
    achieved = models.IntegerField()
    remarks = models.CharField(max_length = 255)
    efficiency = models.FloatField()
    incentive_received = models.FloatField(default=0.0)



    def __str__(self):
        return f"{self.partial_shift}"

    def save(self, *args, **kwargs):

        if not self.pk:  # If this is a new instance
            print("in saving--------------------.............------------")
            remarks = self.remarks.lower()
            self.efficiency = (self.achieved/self.target)*(self.shift_duration/self.partial_shift)*100
            print(f"Achieved : {self.achieved}\n Target : {self.target}\n shift_duration : {self.shift_duration}\n partial shift :{self.partial_shift}")
            print(f"Efficiency value: {self.efficiency}")

            external_instance = Externals.objects.filter(parameter=self.remarks).first()
            efficiency_value= external_instance.value * 100


            if self.efficiency<efficiency_value and remarks not in ['2M1P']:
                print("********************________________________Entering the function that updates efficiency____________***********")
                print(f"Efficiency Value:{efficiency_value}")
                self.efficiency=efficiency_value
            print("Saved!")

        # self.incentive_received = round(self.incentive_received, 2)

        self.incentive_received = round(self.incentive_received, 2)

        super().save(*args, **kwargs)


class Breakdown(models.Model):
    id = models.AutoField(primary_key=True)
    date = models.DateField()
    tool_code = models.ForeignKey(Tool,on_delete=models.CASCADE,related_name='breakdown_tool_code',to_field='tool_code')
    machine_id = models.ForeignKey(NewMachine, on_delete=models.CASCADE, db_column='machine_id', to_field='machine_id')
    length_used = models.FloatField()
    expected_length_remaining = models.FloatField()
    replaced_by = models.ForeignKey(Tool, on_delete=models.CASCADE, related_name='breakdown_replaced_by',db_column='replaced_by', to_field='tool_code')
    reason = models.CharField(max_length=100) #remarks
    change_time = models.IntegerField()
    no_of_min_into_shift = models.IntegerField()
    emp_ssn=models.ForeignKey(Employee2,on_delete=models.CASCADE,to_field='emp_ssn')
    achieved = models.IntegerField()
    shift_number = models.IntegerField()


    def __str__(self):
        return f"{self.tool_code}"




class Reviving1(models.Model):
    tool_code=models.OneToOneField(Tool,on_delete=models.CASCADE,primary_key=True)
    date=models.DateField()
    def __str__(self):
        return f"{self.tool_code}"


class ToolChart(models.Model):
    tool_code = models.CharField(max_length=50)
    no_of_brk_points = models.IntegerField()
    tool_efficiency = models.FloatField()
    part_no_count = models.IntegerField()

    def __str__(self):
        return self.tool_code



class Auth(models.Model):
    role = models.CharField(max_length=40)
    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

    def __str__(self):
        return self.username


class SignAuth(models.Model):

    username = models.CharField(max_length=30)
    password = models.CharField(max_length=30)

    def __str__(self):
        return self.username



# class ShiftEfficiency(models.Model):
#     id = models.BigAutoField(primary_key=True, auto_created=True,default=None)
#     date = models.DateField()
#     shift_number = models.IntegerField()
#     shift_efficiency = models.FloatField()
#
#     def __str__(self):
#         return f"{self.shift_number}"



#----------------------Post updation of performs table--------------

    #Tool table updation
# def tool_table_updation(sender,instance,created,**kwargs):

#     machine_id = instance.machine_id

#     machine_instance=get_object_or_404(Machine,machine_id=machine_id)
#     tool_code = machine_instance.tool_code
#     print("In tool table updation!")
#     part_no = machine_instance.part_no


#     job_tuple=get_object_or_404(Job,tool_code=tool_code,part_no=part_no)

#     depth_of_cut = job_tuple.depth_of_cut

#     no_of_holes=job_tuple.no_of_holes

#     additional_length=depth_of_cut*no_of_holes


#     tool_tuple=get_object_or_404(Tool,tool_code=tool_code)
#     tool_tuple.length_cut_so_far+=additional_length

#     tool_tuple.save()


#     new_efficiency=calculate_tool_efficiency(tool_code,tool_tuple.length_cut_so_far)
#     tool_tuple.tool_efficiency=new_efficiency
#     tool_tuple.save()

# post_save.connect(tool_table_updation,sender=Performs)


j = 0  # Global variable to track function execution


def tool_table_updation(sender, instance, created, **kwargs):
    global j  # Declare j as global to modify it inside the function
    if j == 1:
        print("Function has already been called once, skipping execution.")
        j=0
        return

    print("=================Function is called!========================")
    try:
        machine_id = instance.machine_id
        achieved = instance.achieved

        machine_instances = Machine.objects.filter(machine_id=machine_id)
        print(machine_instances)
        for machine_instance in machine_instances:
            tool_code = machine_instance.tool_code
            print("tool_code is ....")
            print(tool_code)
            part_no = machine_instance.part_no
            print("part_no is ....")
            print(part_no)
            # job_tuple = Job.objects.get(tool_code=tool_code, part_no=part_no)

            # depth_of_cut = job_tuple.depth_of_cut
            # no_of_holes = job_tuple.no_of_holes
            # additional_length = achieved * depth_of_cut * no_of_holes
            # print("Additional Length")

webapp/templates/webapp/breakdown_form.html
<!-- breakdown_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Breakdown Data</title>
</head>
<body>
    <h1>Breakdown Data</h1>
    <table border="1">
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Length Used</th>
                <th>Expected Length Remaining</th>
                <th>Replaced By</th>
                <th>Reason</th>
                <th>Change Time</th>
                <th>Hours into Shift</th>
                <th>Machine ID</th>
                <th>Tool Code</th>
            </tr>
        </thead>
        <tbody>
            {% for breakdown_item in breakdown_data %}
            <tr>
                <td>{{ breakdown_item.id }}</td>
                <td>{{ breakdown_item.date }}</td>
                <td>{{ breakdown_item.length_used }}</td>
                <td>{{ breakdown_item.expected_length_remaining }}</td>
                <td>{{ breakdown_item.replaced_by }}</td>
                <td>{{ breakdown_item.reason }}</td>
                <td>{{ breakdown_item.change_time }}</td>
                <td>{{ breakdown_item.no_of_min_shift }}</td>
                <td>{{ breakdown_item.id }}</td>
                <td>{{ breakdown_item.tool_code.tool_code }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

webapp/templates/webapp/employee_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Employee</title>
</head>
<body>

  <h2>Delete Employee</h2>
  <p>Are you sure you want to delete "{{ employee.emp_name }}"?</p>
  <form method="post" action="{% url 'employee_delete_view' employee.emp_ssn %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>

</body>
</html>

webapp/templates/webapp/employee_efficiency_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Overall Efficiency</title>
</head>
<body>
    <h1>Employee Overall Efficiency</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Calculate Efficiency</button>
    </form>

    {% if efficiency is not None %}
        <p>Efficiency: {{ efficiency }} %</p>
    {% endif %}
</body>
</html>

webapp/templates/webapp/employee_efficiency_form_date.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee Efficiency</title>
</head>
<body>
    <h1>Employee Efficiency</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Calculate Efficiency</button>
    </form>

    {% if efficiency is not None %}
        <p>Efficiency: {{ efficiency }} %</p>
    {% endif %}
</body>
</html>

webapp/templates/webapp/employee_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Employee</title>
</head>
<body>

  <h2>Update Employee</h2>
  <form method="post" action="{% url 'employee_update_view' employee.emp_ssn %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>

</body>
</html>

webapp/templates/webapp/job_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Job</title>
</head>
<body>

  <h2>Delete Job</h2>
  <p>Are you sure you want to delete "{{ job.job_name }}"?</p>
  <form method="post" action="{% url 'job_delete_view' job.job_id %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>

</body>
</html>

webapp/templates/webapp/job_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create a New Job</title>
    <!-- Add any additional CSS or scripts here -->
    <style>
        /* Add your custom styles here */
    </style>
</head>
<body>

  <h2>Create a New Job</h2>
  <form method="post" action="{% url 'job_create_view' %}" id="job-form">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="id_job_id">Job ID</label>
    <input type="text" name="job_id" id="id_job_id"><br>

    <label for="id_job_name">Job Name</label>
    <input type="text" name="job_name" id="id_job_name"><br>

    <div id="tools-fields">
      {% for tool in tools %}
        <label>
          <input type="checkbox" name="tools" value="{{ tool.tool_code }}" data-tool-code="{{ tool.tool_code }}">
          {{ tool.tool_name }}
        </label>
        <div class="tool-details" id="{{ tool.tool_code }}" style="display:none;">
          <label for="id_length_{{ tool.tool_code }}">Length for {{ tool.tool_name }}</label>
          <input type="text" name="length_{{ tool.tool_code }}" id="id_length_{{ tool.tool_code }}"><br>
          <label for="id_no_of_holes_{{ tool.tool_code }}">Number of Holes for {{ tool.tool_name }}</label>
          <input type="text" name="no_of_holes_{{ tool.tool_code }}" id="id_no_of_holes_{{ tool.tool_code }}"><br>
        </div>

      {% endfor %}
    </div>

    <button type="submit">Create Job</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  <script>
    $(document).ready(function () {
      // Show/hide fields based on tool selection
      $("input[name='tools']").change(function () {
        var toolCode = $(this).data("tool-code");
        var toolDetailsDiv = $("#" + toolCode);

        if ($(this).prop("checked")) {
          toolDetailsDiv.show();
        } else {
          toolDetailsDiv.hide();
        }
      });
    });
  </script>

</body>
</html>

webapp/templates/webapp/machine_form.html
<!-- machine_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create a New Machine</title>
</head>
<body>

<h2>Create a New Machine</h2>
<div id="machine-details">
    <label for="id_machine_id">Machine ID</label>
    <input type="text" name="machine_id" id="id_machine_id"><br>

    <label for="id_machine_name">Machine Name</label>
    <input type="text" name="machine_name" id="id_machine_name"><br>

    <label for="jobs">Select Job(s)</label>
    {% for job in jobs %}
        <label>
            <input type="checkbox" name="jobs" value="{{ job.id }}" class="job-checkbox"> {{ job.job_name }}
        </label>
        <div class="tool-details" id="tools_{{ job.id }}" style="display:none;">
            <label for="tools">Tool(s) for {{ job.job_name }}</label>
            <div id="tool-list_{{ job.id }}"></div>
            <br>
            <label for="tool_code_{{ job.id }}">Tool Code</label>
            <input type="text" name="tool_code_{{ job.id }}" id="tool_code_{{ job.id }}"><br>
        </div>
    {% endfor %}
</div>

<button type="button" onclick="createMachine()">Create Machine</button>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    function createMachine() {
        // Implement your logic to handle machine creation
    }

    $(document).ready(function () {
        // Show/hide tool details based on job selection
        $(".job-checkbox").change(function () {
            var jobId = $(this).val();
            var toolsDiv = $("#tools_" + jobId);

            if ($(this).prop("checked")) {
                toolsDiv.show();
                loadToolNames(jobId);
            } else {
                toolsDiv.hide();
            }
        });
    });

    function loadToolNames(jobId) {
        $.ajax({
            type: 'GET',
            url: '/get_tool_names/',  // Replace with the actual URL to retrieve tool names for a job
            data: {job_id: jobId},
            success: function (data) {
                $("#tool-list_" + jobId).html('(' + data.tool_names + ')');
            },
            error: function () {
                console.log('Error loading tool names.');
            }
        });
    }
</script>

</body>
</html>

webapp/templates/webapp/shift_efficiency_form_date.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shift Efficiency</title>
</head>
<body>
    <h1>Shift Efficiency</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Calculate Efficiency</button>
    </form>

    {% if efficiency is not None %}
        <p>Efficiency: {{ efficiency }} %</p>
    {% endif %}
</body>
</html>

webapp/templates/webapp/success_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success Page</title>
</head>
<body>
    <h1>Form Submitted Successfully!</h1>
    <p>Thank you for submitting the form.</p>
    <!-- You can add more content or styling as needed -->
</body>
</html>

webapp/templates/webapp/tool_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Tool</title>
</head>
<body>

  <h2>Delete Tool</h2>
  <p>Are you sure you want to delete "{{ tool.tool_name }}"?</p>
  <form method="post" action="{% url 'tool_delete_view' tool.tool_code %}">
    {% csrf_token %}
    <button type="submit">Delete</button>
  </form>

</body>
</html>

webapp/templates/webapp/tool_efficiency_form.html
<!-- tool_efficiency_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tool Efficiency Calculation</title>
</head>
<body>
    <h1>Tool Efficiency Calculation</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Calculate Efficiency</button>
    </form>
    {% if efficiency is not None %}
        <p>Tool Efficiency: {{ efficiency }} %</p>
    {% endif %}
</body>
</html>

webapp/templates/webapp/tool_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Tool Form</title>
</head>
<body>

<h2>Tool Form</h2>

<form method="post" action="{% url 'tool_create_view' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>

</body>
</html>

webapp/templates/webapp/tool_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Tool</title>
</head>
<body>

  <h2>Update Tool</h2>
  <form method="post" action="{% url 'tool_update_view' tool.tool_code %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
  </form>

</body>
</html>